name: Python CI Pipeline

on: [push, pull_request]  # Runs on every push and pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Clones the repo

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use Python 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run PyLint (Code Linting)
        run: |
          pylint calculator.py || true  # Run lint check

      - name: Run Unit Tests
        run: |
          python -m unittest discover
